/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pie_chart_observer_ufu;

import pie_chart_observer_ufu.chart.BarChartObserver;
import pie_chart_observer_ufu.chart.PieChartObserver;

import javax.swing.*;
import java.awt.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Sets up an initial set of three courses
     *
     * @param args not used
     */
    public static void main(String[] args) {

        CourseRecordSubject subject = new CourseRecordSubject();
        CourseData data = new CourseData(subject);
        data.addCourseRecord(new CourseRecord("Physics", 50));
        data.addCourseRecord(new CourseRecord("Chemistry", 50));
        data.addCourseRecord(new CourseRecord("Biology", 50));

        CourseController controller = new CourseController(data);
        subject.attach(controller);

        BarChartObserver bar = new BarChartObserver(data.getUpdate());
        subject.attach(bar);
        JScrollPane barScrollPane = new JScrollPane(bar,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

        PieChartObserver pieChart = new PieChartObserver(data.getUpdate());
        subject.attach(pieChart);
        JScrollPane pieScrollPane = new JScrollPane(pieChart,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);


        JFrame frame = new JFrame("Observer Pattern");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().setLayout(new GridBagLayout());
        frame.setResizable(false);

        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.BOTH;
        constraints.weightx = 0.25;
        constraints.weighty = 1.0;
        constraints.gridx = 0;
        constraints.gridy = 0;
        frame.getContentPane().add(controller, constraints);
        constraints.weightx = 0.5;
        constraints.weighty = 1.0;
        constraints.gridx = 1;
        constraints.gridy = 0;
        frame.getContentPane().add(barScrollPane, constraints);
        constraints.weightx = 0.5;
        constraints.weighty = 1.0;
        constraints.gridx = 1;
        constraints.gridy = 1;
        frame.getContentPane().add(pieScrollPane, constraints);
        frame.pack();
        frame.setVisible(true);
    }
}
